### ISSUE TITLE
please fork the following ontology related repositories

### ISSUE THREAD

**Issue by egonw** [OpenRiskNet/home#1]
The following repositories need to be forked into OpenRiskNet organisation. Please give me admin rights to these two repositories, so that I can set up use of Wiki, trackers, Projects, etc... (and, importantly, assign people to tasks.

* https://github.com/egonw/orn-ontology
* https://github.com/egonw/orn-ontotest

**Comment by joahim** [comment]
Forked.

**Comment by tdudgeon** [comment]
Currently the ability to create a repo is only available to people designated as owners of the OpenRiskNet organisation. We can instead allow all members to create, but this is probably not a good idea.
There's no problem making other members (like Egon) owners, but we really need a policy on how we go about this.
This is briefly described here: https://github.com/OpenRiskNet/home/wiki/Development-Guidelines

**Comment by egonw** [comment]
@tdudgeon, I think it's fine to keep the list of owners small. I'm more than fine with taking this route. Just to clarify my point in the issue report, I was talking about admin on the repository, not the whole organisation. Quite confident that that is possible.

@joahim, thanks!

**Comment by egonw** [comment]
@tdudgeon, if you mean you want to have all repositories with the same functionality, then that's fine for me too. E.g. I note the new ontology repo does not have issues turned on. Can I conclude from that that issues should go to the /home/ repository?

**Comment by joahim** [comment]
@egonw Issues enabled

**Comment by egonw** [comment]
I don't seem to have push access yet...

**Comment by tdudgeon** [comment]
@egonw I set up the Developers team to have write access to both repos. This should give you the access you need. But it may not be the best approach as:
1. it does not give you admin rights to the repos
1. you might not want all members of that team to have edit access

So we might want to consider setting up finer grain access.

**Comment by tdudgeon** [comment]
Can this be closed now?
