### ISSUE TITLE
Jupyter PDF export not working

### ISSUE THREAD

**Issue by egonw** [OpenRiskNet/home#10]
.. bc pandoc is not installed.

Reproduce by making a simple python 3 notebook and selecting Export as PDF.

**Comment by tdudgeon** [comment]
I tried enabling PDF export for a notebook and it seemed to required adding a huge number of packages which make the images size much bigger. A whole lot of things like LaTex support was added.
I'm not sure if there is a more lightweight approach to this.

**Comment by egonw** [comment]
Okay, so not a bug, but a feature.
