### ISSUE TITLE
Font problem with Jupyter notebooks

### ISSUE THREAD

**Issue by tdudgeon** [OpenRiskNet/home#12]
Reported by Thomas:

I ran into a problem with the jupyter notebook on the reference instance: /opt/app-root/lib/python3.5/site-packages/matplotlib/font_manager.py:1297: UserWarning: findfont: Font family ['sans-serif'] not found. Falling back to DejaVu Sans
 (prop.get_family(), self.defaultFamily[fontext])) I don't really care what font is used but unfortunately no graph is produced. Could https://stackoverflow.com/questions/42097053/matplotlib-cannot-find-basic-fonts help?

**Comment by GrahamDumpleton** [comment]
Do you have a public link to a notebook file that demonstrates the issue?

**Comment by GrahamDumpleton** [comment]
Likely needs the ``open-sans-fonts`` system package installed if not a default font. Questions is how many fonts do you try and install by default. Do you also try and install common Microsoft fonts as well.

**Comment by danyx23** [comment]
Hi Graham, the notebook that this was reported with is attached to this comment. The problem apparently occured only when the "SciPy notebook" is selected in the spawner options and when the "seaborne" plotting package is used. When using the "Minimal notebook" image and installing the required packages with `!pip install ...` from the jupyter notebook then the error could not be reproduced. So maybe this is just a particular problem of the versions of the related python libraries and the os packages as they are configured in the SciPy notebook docker image?

**Comment by tdudgeon** [comment]
Won't fix.
