### ISSUE TITLE
Modelling web has lost its keycloak connection

### ISSUE THREAD

**Issue by tdudgeon** [OpenRiskNet/home#14]
When PostgreSQL and Keycloak needed to be re-installed (about 2 weeks ago) it was necessary to re-connect apps to Keycloak. It seems that this has not yet been done for Modelling Web as you get a 'Client not found' error from Keycloak.
This means that the cient needs to be created again in the openrisknet realm, and MW updated to use the new secrets etc.

**Comment by jonalv** [comment]
Solved, now runs with Keycloak
