### ISSUE TITLE
End user authentication

### ISSUE THREAD

**Issue by tdudgeon** [OpenRiskNet/home#2]
We need to decide how we will authenticate end users for out ORN reference site.
Keycloak provides many approaches that can be used. Se [here](http://www.keycloak.org/docs/latest/server_admin/index.html#_identity_broker) and [here](http://www.keycloak.org/docs/latest/server_admin/index.html#_user-storage-federation) for details.
Each VRE can take whatever approach is best for that organisation, but for the ORN reference site we need to decide what is best.
The most obvious choices are:
1. Store user details (including usernames and passwords) within the system, and allow users to register themselves.
2. Federate out using one of the supported social logins.

My personal preference is to federate out to the LinkedIn social login. The reasons are:
1. we do not need manage user's personal information and reduce the liability of security hacks.
2. LinkedIn users (unlike Google, Facebook etc.) most consists of real people, and represents their professional persona (no pictures of cats!).
3. Potentially provides access to collaboration and social features using LinkedIn

However:
1. Not every potential user may have a LinkedIn account
2. We can support multiple approaches

Please add your thoughts to this issue.

**Comment by jonalv** [comment]
What are the problems of supporting multiple approaches? I don't see any for the moment but I am probably naïve...

**Comment by tdudgeon** [comment]
@jonalv I don't think there are any technical problems with supporting multiple approaches. Just that if we did so (e.g. allow login through LinkedIn and GitHub) we reduce the ability to utilise those resources (e.g. collaboration through LinkedIn)

**Comment by tdudgeon** [comment]
Closing this issue as we have LinkedIn and GitHub providers implemented.
Open a new issue if another provider is needed.
