### ISSUE TITLE
Spawn Custom Jupyter notebook environments

### ISSUE THREAD

**Issue by evanfloden** [OpenRiskNet/home#20]
Currently users have the choice of 3 default Jupyter notebook environments (a.k.a. Job Profiles) to spawn up on the ORN infrastructure.

Ideally we could provide notebooks which contain the tools/kernel developed by ORN partners and others already installed.

This notebook environment can then be spawned and the user can simply run any tool on demand via BASH or Python or even custom kernels such as R.

In our example, we would require Java and Nextflow.

**Comment by tdudgeon** [comment]
Custom notebook images are now possible [docs](https://github.com/OpenRiskNet/jupyter-notebook-images/blob/master/README.md) and we now have a basic Nextflow one [here](https://github.com/OpenRiskNet/notebooks). There is also one present on the site for R (though that one is pulled direrctlly from Docker Hub)

So closing this issue now.
