### ISSUE TITLE
Need for text mining / mapping for AOP-Wiki contents

### ISSUE THREAD

**Issue by marvinm2** [OpenRiskNet/home#37]
There is a need for identification of genes, proteins, metabolites described in text in Key Events and Key Event Relationships.

Also, methods and approaches are described on how to test for a Key Event. Extracting this data would be useful as well. 

AOP-Wiki RDF Virtuoso docker should allow extracting these pieces of text.

Which tools would fit this purpose?

**Comment by egonw** [comment]
I recommend looking at the [ContentMine](http://contentmine.org/) stack. if we're going to take this forward.

**Comment by egonw** [comment]
Marvin, please add which items you like to extract. For genes (human, mouse) there is already existing code. For other things, a dictionary (=list of words it should recognize) would make it trivial too.
