### ISSUE TITLE
Make sure the AOPLink case study description is in place in Google Drive

### ISSUE THREAD

**Issue by marvinm2** [OpenRiskNet/home#39]
It is not in the folder, but located in trash (so Lucian might be able to recover it)

This is necessary for Deliverable report

**Comment by lucfar** [comment]
The document was recovered, here is the [link](https://docs.google.com/document/d/1k_Jzsbt0reicpE3-RZ_o_0ixwGqYqB7i_mysdl4Egk4/edit). I hope is the latest version, as I could not find any other version in Trash or in the Folder.
