### ISSUE TITLE
Provide trusted certificates for SSO

### ISSUE THREAD

**Issue by tdudgeon** [OpenRiskNet/home#4]
The current SSO server (Keycloak) uses self signed certificates so the user is warned that the site is insecure. We need to change this so that trusted certificates are used and that they are renewed before they expire.
Bill de Coste from Red Hat is providing us with advice on how best to achieve this.

**Comment by rautenberg** [comment]
Free Let's Encrypt certificates could be a solution here (https://letsencrypt.org/) . They are mostly trusted by browsers (https://letsencrypt.org/docs/certificate-compatibility/). We have used them together in a docker environment with a Nginx Proxy in a Docker container https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/ which allowed the creation/renewal of the certificates automatically.

**Comment by tdudgeon** [comment]
Yes, that's the plan. It's a question of how to implement it as the setup for Keycloak is reasonably complex. We're discussing this with Red Hat.

**Comment by Pantelispanka** [comment]
We also use Micha's approach, for applications that are living in a single
host and docker containers, and we are trying to migrate this to an
Openshift - Kubernetes envoronment.
I will let you know if we succed on that!

2017-11-24 10:34 GMT+02:00 Tim Dudgeon <notifications@github.com>:

**Comment by tdudgeon** [comment]
Do note that this discussion ONLY really relates to certificates for Keycloak. 
For normal applications we already have an approach for handling certificates using the ACME Controller which completely automates the process in a very simple manner. See these links for how it works:
https://github.com/OpenRiskNet/home/tree/master/openshift/recipes/certificates
https://github.com/OpenRiskNet/home/tree/master/openshift/deployments/acme-controller
https://github.com/tnozicka/openshift-acme

**Comment by tdudgeon** [comment]
This was resolved by using OpenShift ACME to deploy Let's Encrypt certs just like other projects.
