### ISSUE TITLE
OpenRiskNet vs TeSS events description

### ISSUE THREAD

**Issue by lucfar** [OpenRiskNet/home#45]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1ACcd4HDmR4f85QxNr_uHiZnCO6NgMiCmADSF_1luZcM/edit#gid=486452124) including "Elixir's TeSS Online Event" headings and the content that can retrieve from the "[OpenRiskNet Events](https://openrisknet.org/events/)" current description.

Few notes are added, where I saw some incompatibilities or columns that need some attention.

**Comment by egonw** [comment]
Do those website page have BioSchemas in it? If not, we can indeed use the trick to have JSON-LD  BioSchemas (see http://bioschemas.org/specifications/Event/) for each.

For now, I [registered them by hand](https://tess.elixir-europe.org/content_providers/openrisknet) (from the website, which is not identical to the spreadsheet):

![image](https://user-images.githubusercontent.com/26721/53694630-d004ec00-3db1-11e9-89b0-6c6a4786be4e.png)

**Comment by lucfar** [comment]
1) The events' pages don't have a BioSchemas but it can be included. Let me bring Maja @ciperus into the discussion and see how these schemas can be included in the Events description page and how this will work.
2) Indeed, the spreadsheet is not identical with the website. The spreadsheet contains the headings required by TeSS, while the website contains a slightly different description and headings.

**Comment by egonw** [comment]
@lucfar, I had a go at it: https://openrisknet.github.io/tess/sitemap.xml

**Comment by egonw** [comment]
Continued in the emerging [ELIXIR Tox community](https://github.com/BiGCAT-UM/ELIXIR-Tox).
