### ISSUE TITLE
setup ELIXIR AAI on home.prod

### ISSUE THREAD

**Issue by egonw** [OpenRiskNet/home#48]
@Chris-Evelo, Tim wrote this after lunch about ELIXIR AAI:

```
basically I need an endpoint such as https://login.elixir-czech.org/oidc/.well-known/openid-configuration
(mentioned here: https://docs.google.com/document/d/1vOyW4dLVozy7oQvINYxHheVaLvwNsvvghbiKTLg7RbY/edit). 
So just need to coordinate on the specific details with the appropriate people.
```

Can you please put @tdudgeon  in contact with the right people about this technical question?

**Comment by Chris-Evelo** [comment]
Done, sent email to Ludek Matyska and Tommy Nyronen who lead the ELIXIR compute platform with Tim in cc.

**Comment by tdudgeon** [comment]
This was implemented. Logging in through AAI is now available.

**Comment by egonw** [comment]
Tried and confirmed. Thanks, awesome!!!

**Comment by egonw** [comment]
Various people in the EU NanoSafety Cluster may use it. I've proposed it as a cloud solution for some work we'll be doing: https://github.com/NanoCommons/wgf-fairdata-analysis cc @thomasexner
